### ISSUE TITLE
demultiplexing - how to skip or specify

### ISSUE THREAD

**Issue by OndroV** [Saskia-Oosterbroek/decona#11]
Hi,
are there any options to customize demultiplexing, please?
For example to use custom tags (indexes/barcodes). For Illumina pipelines we usually supply the fastq files and a file linking specified tag combinations to sample names. I see that Qcat doesn't offer such option, so I wonder if any software from ONT allows that. 
Thus, it might be easier to run decona on files that are already demultiplexed and quality-filtered. Is this possible? If yes, does the rest of decona pipeline need fastq format or is fasta sufficient as input?
Cheers! Ondro

**Comment by OndroV** [comment]
Hi, I found a workaround for demultiplexing with custom tags. But it is not an ideal solution, so it would still be nice if decona would recognize custom tags or fasta files as input. @Saskia-Oosterbroek

**Comment by Saskia-Oosterbroek** [comment]
Hello Ondro,

Unfortunately at the moment there is no option for custom tags, indeed the ONT software doesn’t offer that. We also do not plan to add this feature anytime soon as we generally use the Nanopore barcodes.

You can use already demultiplexed files in fastq format, for this to work they need to be stored in folders according to the barcode number. This is also the format in which your data would already be stored in case you have demultiplexed on the Nanopore MK1c for instance.

Example folder structure:
```
working-directory
|--- barcode01/
|    └ barcode01.fastq
|--- barcode02/
|    └ barcode02.fastq
|--- barcode03/
     └ barcode03.fastq
```

Instead of using the -d flag for demultiplexing you can use the -f flag for folder structure (and still do quality filtering if needed). 

`Decona -f -q 10 -l 600 -m 800 -M`

For now I don’t dare to guarantee this will work flawlessly with custom names. I’ll check and fix that for the new version (Decona1.3) which I hope to release later this week.

I hope this is useful to you,
Saskia

**Comment by OndroV** [comment]
Hi, OK thanks for looking into this. I managed to get some nice results even with custom names.

**Comment by OndroV** [comment]
Good news for anyone working with custom libraries: [Barbell Resolves Demultiplexing and Trimming Issues in Nanopore Data](https://doi.org/10.1101/2025.10.22.683865)
Cheers,
Ondrej
