### ISSUE TITLE
install issue v1.2 and v1.3

### ISSUE THREAD

**Issue by thierryjanssens** [Saskia-Oosterbroek/decona#36]
Hi,

I have an install issue with v1.2 and v1.3.

~/git/decona-1.3/install$ bash ./install.sh 
Building CD-HIT...
make: *** No targets specified and no makefile found.  Stop.

This happens both with the cloned as the untarred version (respectively v1-2 and v1-3).

Regards,

Thierry

**Comment by thierryjanssens** [comment]
Hi,

accrding to the comments in the install.sh script, I have added the --recurse-submodules argument to the git command.
This is however also not working.

regards,

Thierry

$ git clone --recurse-submodules https://github.com/Saskia-Oosterbroek/decona.git
Cloning into 'decona'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 151 (delta 56), reused 62 (delta 18), pack-reused 0
Receiving objects: 100% (151/151), 6.49 MiB | 2.77 MiB/s, done.
Resolving deltas: 100% (56/56), done.
Submodule 'external/cdhit' (git@github.com:weizhongli/cdhit.git) registered for path 'external/cdhit'
Cloning into '/home/minion/git/decona/external/cdhit'...
/etc/ssh/ssh_config: line 52: Bad configuration option: permitrootlogin
/etc/ssh/ssh_config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:weizhongli/cdhit.git' into submodule path '/home/minion/git/decona/external/cdhit' failed
Failed to clone 'external/cdhit'. Retry scheduled
Cloning into '/home/minion/git/decona/external/cdhit'...
/etc/ssh/ssh_config: line 52: Bad configuration option: permitrootlogin
/etc/ssh/ssh_config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:weizhongli/cdhit.git' into submodule path '/home/minion/git/decona/external/cdhit' failed
Failed to clone 'external/cdhit' a second time, aborting

**Comment by thierryjanssens** [comment]
Installing cd-hit manually is also not resolving the issue.

git/decona/external/cdhit is an empty folder.

**Comment by Saskia-Oosterbroek** [comment]
Hi Thierry,
The issue is probably caused by the SSH-configuration on your computer. You will probably not be the only one so Cees just updated the install file to use HTTPS instead of SSH. I hope this will solve your issue!
Best,
Saskia

**Comment by thierryjanssens** [comment]
Dear Sakia,

the problem remains. Moreover, there is no ssh mentioned in install.sh, as I downloaded it a couple of minutes ago.

Kind regards,

Thierry

**Comment by ceesvoesenek** [comment]
Hi Thierry,

Apologies for the confusion (and the delay), it is indeed (in hindsight) expected that it does not work when downloading as a release. We now load CD-HIT as a git submodule instead of installing it from Anaconda, because the Anaconda version does not support multithreading. For this reason, it needs to be a git repository to be able to clone these submodules. The change from SSH to HTTPS happened in the specification of this submodule, not in the install script.

I will look into fixing this problem for non-cloned repositories and fix it in the install script.

For now, can you try to clone the repository with git:
`git clone --recurse-submodules https://github.com/Saskia-Oosterbroek/decona.git`
and see if works then?

You may need to install g++ and zlib to build CD-HIT, under Ubuntu, this can be done with:
`sudo apt install g++ zlib1g-dev`
I will also add checks to the install script to verify the presence of these dependencies.

Thanks for reporting, best regards,
Cees

**Comment by thierryjanssens** [comment]
Thanks.
It seems to work.
