### ISSUE TITLE
Example data error before re-clustering

### ISSUE THREAD

**Issue by Statesanalytical** [Saskia-Oosterbroek/decona#39]
Hi Saskia,

I've been trying to run your example datasets with a virtual machine and your new v1.3 with the following command:

decona -f -l 1800 -m 2500 -q 10 -c 0.80 -n 25 -M -r

However, it completes the first round of polishing but then produces the below error before it starts re-clustering:

Blast Racon sequences finished
awk: run time error: not enough arguments passed to sprintf("%d	(%.2f%)")
	FILENAME="combined2.txt" FNR=1 NR=1

I'm not sure if this is related to #23? Is there any way around this? I'm fairly new to bioinformatics so don't particularly understand the script! Also thank you for creating and sharing this pipeline, it will be incredibly useful for beginners like myself

Many thanks,
Luke

**Comment by Robvh-git** [comment]
Hi Luke,

I've experienced the same issue (with decona v1.3.1). The likely issue is your ```awk``` version.

If you run ```awk -W version``` in the decona environment it will likely state that you have awk version 1.3.3 or something like that.

To fix this, run following command in the decona environment:
```
sudo apt update
sudo apt install gawk
```
You can check if it worked by running ```awk -W version``` again. Now you see ```GNU awk 4.1.4``` and the problem is fixed.

**Comment by Statesanalytical** [comment]
Hi Robert,

I ran the commands you suggested and it worked perfectly after that! Thank you for your help, very much appreciated

Cheers,
Luke
